"""init

Revision ID: d77a796ed2b0
Revises: 
Create Date: 2020-03-29 18:09:40.648561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a796ed2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('samples',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('fixed_acidity', sa.String(), nullable=False),
    sa.Column('volatile_acidity', sa.String(), nullable=False),
    sa.Column('citric_acid', sa.String(), nullable=False),
    sa.Column('residual_sugar', sa.String(), nullable=False),
    sa.Column('chlorides', sa.String(), nullable=False),
    sa.Column('free_sulfur_dioxide', sa.String(), nullable=False),
    sa.Column('total_sulfur_dioxide', sa.String(), nullable=False),
    sa.Column('density', sa.String(), nullable=False),
    sa.Column('ph', sa.String(), nullable=False),
    sa.Column('sulphates', sa.String(), nullable=False),
    sa.Column('alcohol', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
